AllCops:
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
