development: &dev
  secret_key_base: 1d1a4c6f2e112185ef3bff349123fd3eb3c8d9c5d00c6f3ff6617c22365c8e46f2bbaf63ae1a607edcde6c5c4fd7a5d45fea79bc68c10e812c5e64534e724642

  telegram:
    bot:
      token: <%= ENV.fetch("TELEGRAM_BOT_TOKEN") %>
      username: <%= ENV.fetch("TELEGRAM_BOT_USERNAME") %>
      # async: true
      # botan:
      #   token: botan_token
      #   # async: true

test:
  secret_key_base: 757fa27460aa9dc295837c551b2ab4d850757d2c781f193da1959e9a7d5803698f41a3ee1f7a5d9fa25151658f85feb659c91d3abc837b0afa1fda4840056fbb

  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME

production:
  <<: *dev
